name: Build

on:
    workflow_dispatch: {}
    push:
        tags: ["v*"]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if (Test-Path requirements.txt) { pip install -r requirements.txt } else { Write-Host "No requirements.txt found." }
                  pip install pyinstaller

            - name: Build with PyInstaller
              working-directory: ${{ github.workspace }}
              run: |
                  pyinstaller pyCCDGUI.spec

            - name: Upload EXE artifact
              uses: actions/upload-artifact@v4
              with:
                  name: pySPEC-exe
                  path: dist/pySPEC.exe
    build-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt pyinstaller

            - name: Clean and build
              run: |
                  rm -rf build/ dist/ __pycache__/ *.dmg
                  pyinstaller --windowed --name=pySPEC --icon=assets/icon.icns --add-data="assets:assets" main.pyw

            - name: Create and upload DMG
              run: |
                  hdiutil create -volname "pySPEC" -srcfolder "dist/pySPEC.app" -format UDZO "pySPEC.dmg"

            - uses: actions/upload-artifact@v4
              with:
                  name: pySPEC-macOS
                  path: pySPEC.dmg

    create-draft-release:
        needs: [build-windows, build-macos]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Download Windows artifact
              uses: actions/download-artifact@v4
              with:
                  name: pySPEC-exe
                  path: ./artifacts/windows

            - name: Download macOS artifact
              uses: actions/download-artifact@v4
              with:
                  name: pySPEC-macOS
                  path: ./artifacts/macos

            - name: Create Draft Release
              uses: softprops/action-gh-release@v1
              with:
                  draft: true
                  files: |
                      ./artifacts/windows/pySPEC.exe
                      ./artifacts/macos/pySPEC.dmg
                  name: Release ${{ github.ref_name }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
